name: Bump on schedule or request

on:
  workflow_dispatch:
  schedule:
    # Every 3 hours 23 minutes past the hour
    - cron: "23 */3 * * *"

permissions:
  contents: write

jobs:
  autobump:
    env:
      HOMEBREW_DEVELOPER: 1
    runs-on: macos-26
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: true

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main
        with:
          username: ${{ github.actor }}

      - name: Bump
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew livecheck --tap sdhEmily/tap --newer-only --json | jq -r '.[] | "\(.formula // .cask) \(.version.latest)"' | while read -r pkg version; do
            if brew bump-cask-pr --write-only --no-browse --version="$version" "sdhEmily/tap/$pkg" 2>/dev/null || \
              brew bump-formula-pr --write-only --no-browse --version="$version" "sdhEmily/tap/$pkg" 2>/dev/null; then
              cd "$(brew --repository sdhEmily/tap)"
              git push
            else
              brew bump-cask-pr --no-fork --version="$version" "sdhEmily/tap/$pkg" 2>/dev/null || \
              brew bump-formula-pr --no-fork --version="$version" "sdhEmily/tap/$pkg"
            fi
          done
